#include "mainwindow.h"
#include "core/AppSettings.h"
#include "core/DatabaseManager.h"
#include "core/DbConnectionDialog.h"
#include "core/LoginDialog.h"

#include <QApplication>
#include <QTranslator>
#include <QMessageBox>
#include <QFile>
#include <QLocale>
#include <QCoreApplication>

static void applyStyle(QApplication &app)
{
    bool dark = AppSettings::instance().darkMode();
    // Styles embedded via resources.qrc (prefix "/styles")
    QFile f(dark ? ":/styles/resources/styles/dark.qss"
                 : ":/styles/resources/styles/light.qss");
    if (f.open(QFile::ReadOnly)) {
        app.setStyleSheet(QString::fromUtf8(f.readAll()));
        f.close();
    }
}

static void applyLanguage(QApplication &app, QTranslator &translator, const QString &lang)
{
    app.removeTranslator(&translator);
    // .qm files are generated by lrelease and placed next to the executable
    QString appDir = QCoreApplication::applicationDirPath();
    if (translator.load("edv_system_" + lang, appDir))
        app.installTranslator(&translator);

    app.setLayoutDirection(lang == "ar" ? Qt::RightToLeft : Qt::LeftToRight);
}

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    app.setApplicationName("EDV System");
    app.setApplicationDisplayName("EDV System");
    app.setOrganizationName("EDV-System");
    app.setOrganizationDomain("edv-system.local");
    app.setApplicationVersion("1.0.0");

    QTranslator translator;
    applyLanguage(app, translator, AppSettings::instance().language());
    applyStyle(app);

    // ── Database connection loop ─────────────────────────────────
    bool connected = false;
    while (!connected) {
        // If not yet configured, show connection dialog
        if (!AppSettings::instance().dbConfigured()) {
            DbConnectionDialog dlg;
            if (dlg.exec() != QDialog::Accepted)
                return 0;
        }

        connected = DatabaseManager::instance().connectFromSettings();

        if (!connected) {
            auto btn = QMessageBox::critical(
                nullptr,
                QObject::tr("Database Error"),
                QObject::tr("Could not connect to the database:\n\n%1\n\n"
                            "Do you want to change the connection settings?")
                    .arg(DatabaseManager::instance().lastError()),
                QMessageBox::Yes | QMessageBox::No
            );
            if (btn == QMessageBox::No)
                return 0;
            AppSettings::instance().setDbConfigured(false);
        }
    }

    // ── Login ────────────────────────────────────────────────────
    LoginDialog login;
    if (login.exec() != QDialog::Accepted)
        return 0;

    // Re-apply language in case user changed it at login screen
    applyLanguage(app, translator, AppSettings::instance().language());
    applyStyle(app);

    // ── Main window ──────────────────────────────────────────────
    MainWindow w(login.username(), login.userId(), login.userRole());
    w.show();

    return app.exec();
}
